version: "3.8"
# Запуск docker-compose up -d

services:
  service1:
    image: 1f09a266269e
    container_name: SHOP-ENCOMPONENT__API
    ports:
      - "1010:8080"

  service2:
    image: 1177d685375c
    container_name: SHOP-ENCOMPONENT__SITE
    ports:
      - "1020:3000"

  service3:
    image: 920c4e1de9f1
    container_name: SUPPLY-HANDY__API
    ports:
      - "1030:8080"
    volumes:
      - ./appsettings-handy.json:/app/appsettings.json

  service4:
    image: 1fc8028e1b32
    container_name: SUPPLY-HANDY__FRONTEND
    ports:
      - "1040:3000"
  
  service5:
    image: d1e3e784844f
    container_name: SUPPLY-SISTEMAUTOR__API
    ports:
      - "1050:8080"
    volumes:
      - ./appsettings-encomponent.json:/app/appsettings.json

  service6:
    image: 480382706adf
    container_name: SUPPLY-SISTEMAUTOR__FRONTEND
    ports:
      - "1060:3000"
  
  service7:
    image: 31bcd7a18c2a
    container_name: EMAIL-MAILER
    ports:
      - "1100:8080"
